development:
  database: emily_lime_development
  adapter: mysql2
  username: root 
  password: 
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

# production:
#   adapter: mysql2
#   encoding: utf8
#   database: <%= ENV['emily_lime'] %>
#   username: <%= ENV['emily_admin'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: <%= ENV['RDS_HOSTNAME'] %>
#   port: <%= ENV['RDS_PORT'] %>